apiVersion: skaffold/v1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: rowdy1/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "client/src/**/*.js"
            dest: .
          - src: "client/src/**/*.css"
            dest: .
          - src: "client/src/**/*.html"
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
