kind: Service
apiVersion: v1
metadata:
  name: postgres-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - name: postgres-port-map
      port: 5432
      targetPort: 5432
