kind: Service
apiVersion: v1
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    - name: redis-port-map
      port: 6379
      targetPort: 6379
