kind: Service
apiVersion: v1
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - name: server-port-map
      port: 5000
      targetPort: 5000
